// Generated by scripts/generate-csp-hashes.mjs after `next build` — do not hand-edit.
// See that script's header comment for why this exists (nonce-based CSP cannot work
// against statically generated output; this is the hash-based replacement).

export const CSP_SCRIPT_HASHES: Record<string, string[]> = {
  "/_not-found": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-nbPMV+vSRw1YL2Ntl/HIf02fALVeLlYZ+9CoJRPSt6Y=",
    "sha256-PHKiU0XP/fm9mmCerHY2sDazUlM2BiQ4IYuXKa/slWs=",
    "sha256-0COgdmdkSPKEjKw6ieEDFAfuqLm09UvoUnZCSEhY+Jw=",
    "sha256-sD0SUfNuZ4O5b/oHlPUhOxfDzCk87yBJtvabd1dodYk="
  ],
  "/about": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-8S966BUEHztiKwBVdCT8pQpN45xoSOIDDHmZJ3H/mUI=",
    "sha256-gxkrNDCEr9nvadH/k9nTMVTuGU8FYMx6evfx/Q+kn8k=",
    "sha256-UIYqmIcOx6cIWxfMsy0p02aYzoqKcd54lQF0nm1+U4s=",
    "sha256-ZyLDkDTYgY/NTPaNHeynuR6pa67xWPHe1I49G3xe6j4=",
    "sha256-okaJMN8x/0Senp7eHzj4lAqzS3EfuDKk/CABQy6C7NE=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/careers": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-Z2q5EZOIGyZlfvz/CimNzenYwkRRyCot/dC4DgZsXMA=",
    "sha256-RiloyUqte4YRUuhf9OV/YIOCUsq29m9/j6606hYtTrg=",
    "sha256-cFwv54zJ3kTmta1zABb6oSfIcYE8xNrED8h2D5COnkU=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/cases": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-I7T3nHXRLfOQTOo43DrDvxREYm7iz+EhcgHCQLAd/AE=",
    "sha256-cOVGCv8Qb7lEGDeLk1mbewz2WjR2TIkHmn2O/O8ekG8=",
    "sha256-HEjhgS/dFW8flH5dVAR05Hu0LpEYxz1+l9YxKbbxWSY=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/consultation": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-8S966BUEHztiKwBVdCT8pQpN45xoSOIDDHmZJ3H/mUI=",
    "sha256-y2eveDhyjW/keTTk+s3du3mo6Xhbem8IkX/HavloY5w=",
    "sha256-MgT8iBI4+su6pFOo2AC1RlCGNCit48HVOYo+/9hbBkk=",
    "sha256-beeCKkoURIxRsfYZEn8xoDtcEkI0ug76GAv7+OWSxLY=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/contact": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-8S966BUEHztiKwBVdCT8pQpN45xoSOIDDHmZJ3H/mUI=",
    "sha256-5/kJ+SBG7HTAIdt08uudCEcpqKEQbBJVhVypA8B/1sE=",
    "sha256-/fmOJjpQsvCeO8qKTiab6Ir3/i5WjLLRvSJjg2mO31I=",
    "sha256-nU/07DZBRBjNgbx+XwnuCVbOZmAnJP3TxdROSL/uHO0=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-eUO6ykN5MczHH7g/jUqPPxoVHTsmwed+4CGUKKqN/sQ=",
    "sha256-DZQjubw6kZRfX9AaFiOPPTiktBAKIrbqtkDgtOeB0gU=",
    "sha256-1agmLd/USWEB/Bevyp/mwUltYmyb6SvaD4y4e+7pyrk=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA=",
    "sha256-jAiirSjY91iN6vehqwvpJEIVyMbA6Mp/S8MDLMaL4og=",
    "sha256-AvqXc8WhZKGXK4UPzoV1ETXNQgl43b+Agugj/8lsm3Q="
  ],
  "/insights": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-8S966BUEHztiKwBVdCT8pQpN45xoSOIDDHmZJ3H/mUI=",
    "sha256-yd9kqgC4UYIiVh3jyGH4ThukwiaYVbqQ89qg2xIDIJg=",
    "sha256-RBLsBGqrwXpqejwxDNdh2SgvTJsnZVH9DTbwRtL76Z4=",
    "sha256-8KMKPvw8kdgs4ADcFU8KVq1a91/z/dB8G4aTDNBdPdY=",
    "sha256-PIGqHy5+UTrwjNQuKpEhh8r5g1jH2WDf0b0bWdLmHN0=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/people": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-8S966BUEHztiKwBVdCT8pQpN45xoSOIDDHmZJ3H/mUI=",
    "sha256-Z8IK9Q5I65MenvgaPzq5J0OYYGc3ANkp2/+QVeQrIuI=",
    "sha256-dp5N4L5VKeqJPdCwRSIjz42kY7GDp2xZgFwcn6x/kVM=",
    "sha256-ABeAICL3fO9NQyiDFyoYgQjVEP77PeKaMTngGzRq8Xc=",
    "sha256-V0GUvpuOi6WuD2ObIuFjt11Nc6pv0L76aUuc2E1OU78=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/practices": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-8S966BUEHztiKwBVdCT8pQpN45xoSOIDDHmZJ3H/mUI=",
    "sha256-H2CLEwsxyuQ67nrXNlk5kllN29JRbIBMe8imcX+6ZTI=",
    "sha256-upPQ1xwxgdzj0hMudAFBbSMhqXmzIJ2AdOlLIAT25HA=",
    "sha256-hDwsbteJlRQhDO7/wCbVj12oVmoIx90QQ54rmid4cTA=",
    "sha256-WtVUXveauX4g+sFDbEPlTbnDCdCtGqkr/IvK8N8SX0Q=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/recognition": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-8S966BUEHztiKwBVdCT8pQpN45xoSOIDDHmZJ3H/mUI=",
    "sha256-sd3bBaELwv2I7r5n8UpRVQEaErsdR3u9GB8R8F02MGI=",
    "sha256-MSiON1szSmsxKk7cP+1KpAk6+segdPT5WJniF4rwaEQ=",
    "sha256-ejXnHlm/oQ8AupdLVsZy4j1lyVENfqSY7zg6HjkyQ80=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/styleguide": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-F9ZVSecgfm6+xbmE86EK2P0q6XA7XIZBDSUIyP1RJAM=",
    "sha256-3shc+lU9h9dJyKC9OI6xRNLVlzfuQy3Fu6hVlfTu3AQ=",
    "sha256-IZJLQvTwSlrJ//eK7eTMXz0LiBpvUwyr34dUS7fHvdQ=",
    "sha256-94jRmt6DN3TbPqGfmFXrVYjWLckltjGSzpYuVx1p3lA="
  ],
  "/recognition/best-litigation-brand-innovation-2026": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-pLyxGb0BozbemnD74pRhMvHI/DcFwkmH3jN+Eotzv6k=",
    "sha256-vU6AQ9wkWscjz6Skf/DAGMhy4luUNg8bLukRW4gjdfo=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-GAMnY3sd3G7Myw0GuImkqClfkERJiE+12vkOEBZ1UwM=",
    "sha256-zvi510iLYFAVF7+2R4ZiocVRG7YysYMbO29fObK3Atk=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/elite-one-arbitration-litigation-2025": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-cc6Kj/mh84+s6xsotPUlgokb4ZHwetrrvFT5OwiwB9w=",
    "sha256-VLM4fvmemzqCigWUGJdwKcyl27BaUBV9VPaqDceUEx8=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-OyObLacmY+zPhNj0FU6iHQXkk4l7/mG5f0wcbU5H1Qs=",
    "sha256-/DRAZCV2s72aKRbFhWHJps+EjirmuX+NeBJdyRqr8/c=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/elite-one-bankruptcy-2024": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-YY9wtNO/8jPkutWQUgZwRX9I+JSBJiiLkSXG0T9uBJg=",
    "sha256-vI6UantyQCfqN0XcYp1owhLIziwIhuVP+WZ+XC5O5RA=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-/ksPdRtg5eD/HGmGcOK1Ft8Xo8KDFhxTQwzCx/Ll8pE=",
    "sha256-Z9udevz5vfWIc/iKmHgIOM6rOFQM21xzHqEKR8BPOPk=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/elite-one-bankruptcy-2026": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-nWUInG22ey98wIcqFFBGY3GfNNb6cxfT07wvY9rgXH4=",
    "sha256-dzRDh41GlKBvrdtqbNcaBKHS2E+uTdUh+q497jsEUao=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-bdvJ85o4Y6CEP32BVVcE4YxuuClKx5yLTcdNBNeSRWw=",
    "sha256-8q0EkGtS+mYr6vi2Zo/4N3SYW0H7uirigQbDilZfGyM=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/elite-one-islamic-finance-2026": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-Tf5zFFKt+RGfZJ5ku1zEVWl3HGFPkx9PDRzvyVItoFU=",
    "sha256-BeoO346uB42AbYJQ+hBHV19QRRIFdN39WJBONNQ4KT4=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-OOXwLrLUt5OtOoGHusSKWdUGN9qeHlAEsi4l87TTvNY=",
    "sha256-EtTzWY93Auw4nk3HlfqL3UFUNXAGUtHAS4mCp3d4tjs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/elite-one-labor-employment-2025": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-jm+6IRbFV8OUhFIiN6gwR3NhFNku6DnyvfJac0uwNII=",
    "sha256-5N1dtrTwcKxVWUufc0uKQhZGeITFubZs/w6XcnWM1II=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-qD4ht0jB+Am4OsmBgoMTbDTtM2pujIIaxHm8QaGfprU=",
    "sha256-+ByzF1NG0llvFXlKS0RZD8ucGEPMK4HsZfO7kPSzPuQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/largest-litigation-4th-2024": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-OdtbmjF98lInbjJLH6+rpbXCYkPSBxTTFeGydPINocw=",
    "sha256-YFmnMTxgTtEW9Em+Nu4JDvCbGzfDmVmuRuQlnKKVtiE=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-e+7kZ+jWzESesIyzWUpIAN1F2HO5Ge+6B5BuUlbcTUs=",
    "sha256-FjjhzW/IthpKWpJEJ7tLKzunlWrIyRu/lrzS+WkBpJI=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/top-10-largest-litigation-2022": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-9NbdQ0uhBrs5cDlGjD+i0Os4qLPlpsN3D6GeqSWTTWI=",
    "sha256-znF5UvOBg4GHpMN+Vfgde9GHWMAUkqyHwKWCcMMgTY8=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-rtbVmBdylrnuJwgU/Yq/M2Cy4JqCdfWmhKjGvs/YkLk=",
    "sha256-4h5xrGVNQS46ED9fdSgADoZ41Pe19pxADbAUW+Id9M0=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/top-10-largest-litigation-2026": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-d++lHiuFYXNoFNzd//CDS2rVedeJ10R2RZxv3BDBIh8=",
    "sha256-b7guwhHFkotZg+ovli/5CUSC+1nHbRhCbKGNYYk1/Yk=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-fVMd0CpqE+92e6x9PBlLYwP1AyweT7j58TlIESPLpBc=",
    "sha256-Q91fo4Awcw4z4GGALnVAaBE3nvJT2LhjyN/8EldnJ7s=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/recognition/top-100-indonesian-law-firms-2026": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-GQCG16fTX0tTAEEqznwVi1GVyscp9vQpyWUFWuz4dAY=",
    "sha256-hq0W6Q8H48W5zYyiVTBpCd++Q8nmNCO2ARsHAvvVs5A=",
    "sha256-QQTbVmRWkrR8MNvdpR++fC6jxv/wsmxlv4FDnaR+NF8=",
    "sha256-FuavuoS+qcDPamR0cBK+uxhuwmwlIPLlJSjRyThuoTE=",
    "sha256-KHjU3IG8oynGZGeEZk21VxxqZSxS+1elN5ZkeuZ8IF0=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/practices/arbitration": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-DxVSCujq3c44s9zt/OgjAxovLcE0xMjIFbBNtRxGiQA=",
    "sha256-7cfjyHtisVRfSfwyRTj8DYVKFIZkOb6qDFsc/ZdwI7w=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-YjjsxklX4WU0kiRcgdxEHxPecMU8NSedmQ1wisocuSc=",
    "sha256-IvonzLuWCaKgeoXteEhoApJahVi+dymNk5IvyJW1ceU="
  ],
  "/practices/bankruptcy": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-Lp3mbrow9g3BcnK5aVF1LAqT6E2yPkLbRawyWxYuNdE=",
    "sha256-jxSyElvfw0dyJsI4378HoHdhP4QGApi2kaLWsoNfRIU=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-3/jGLZ5naGWip0nb2VYQV460BuY/ydLvxXdk5OPewLA=",
    "sha256-pLwFeFNepYfYpukyr98GGO7+TxJ2A2VFI7UbBQePOuk="
  ],
  "/practices/capital-markets": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-iDhz4zHGk6qcul43viQJMKgvq/d9YcaoaF0FzE12B2A=",
    "sha256-nh7IZoTg2HmJCVLB6WH/A8l+aGgr2IOv74VbIpqME04=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-9imwvgYQRr6Nql7R9RmCVzisC6p65GxHDydVmOhga98=",
    "sha256-1/Rxi1M/XNvjiLd5OrjtMHSXH59i13PkjgPV/GEcA2g=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/practices/civil-litigation": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-TOzKCc9p2Rovc4thAZYhI/5U1cO0n5F7DkV+UI5cQ8o=",
    "sha256-EVCgarAdapGsGIvvh50syMCQdX6II4eeoBevKg0lLdw=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-EjQ9M+MfbDKuBd4OJEqq6RPXEMzzEJM+lRRRs2sLmEY=",
    "sha256-f+wDd7tsowwKb3cmJX2xH1gyLW2g9XWufEZhTjkjQHk="
  ],
  "/practices/commercial-litigation": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-v9pGzuZHjN5a1qbdTh5ID46/3gfCn9fd2L9qrT41SyA=",
    "sha256-hYJqGz7MzqbHLki+Rn//Mj66z6D6b09QSPN1hU0mnf8=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-3skHmdpIEyAr38P3W1LQmmg+/fOm0J5BEiLijjLS41w=",
    "sha256-9XGQ1EmmL2PSW7f9IbzWTlguHh3xu5ciq6cQkMq0HCA="
  ],
  "/practices/competition-antitrust": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-Z7MOn0D4KSa0caAbvqtik/lRrllK3jxSfQrYXRzI9hI=",
    "sha256-rFd0y9HNMraNHsyiQPlpD2qL+09SrzVR5qN0jCRR734=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-9y1ygtFJ0LHTr5uFqLswEkQ/61CNtG1L01sGg/O4wnE=",
    "sha256-qqnqrzn9giq8dUOD5m0UQlyIDXMOYxVuOuF+3NszmGM="
  ],
  "/practices/criminal-litigation": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-0+v9dzQR7rICeWLMQa8qwyOBclla/CkaKFOfMMqhhLA=",
    "sha256-D+q8ND/xR7zx30ekb+qEqNC+oD+ta6IWNqiR8rOGCT0=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-6D5Uo3MSgYuh2xPBAsMt1NW+KmcD7UdsPogI82aSIbA=",
    "sha256-VKIEhhy6vpFTAVqzyyzlL5OylHV+kimPknthKU6rwD0="
  ],
  "/practices/debt-restructuring": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-MolfPX5BVXYmBsSdv01p2F3kmEPCXc8aoNDvyUGLJ5w=",
    "sha256-j2wCX2X/TSwQrg0zO3bq13N7A+//3DX6UYxKhRTxfa8=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-Wb6JdqyCQF+O4RMkgVUzQSrfY4ef23QNETPCGfAdp9Y=",
    "sha256-ekm3t+O6OQiZxJtwenHuTi9gtiI+4mG122qJ5UsC1W0=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/practices/dispute-resolution": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-uiBjDrakd9TtAd/uBE6ljIHkYAr7mil+GtDiVeRV75g=",
    "sha256-pyNz51HlZ3qDvijXIPuyWnFyYQNlgtLkD09FH58Z5EQ=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-NVjeVTbmBDm7tO/2aDUAmMzci+olWgXUOqecidQJt7k=",
    "sha256-yNd+XaPS+tNoixHekmvKZo+cRHqEIqbfvGPgsSxe27s=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/practices/islamic-law": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-dHz0I/SgicwB+APbPT1ZAgtmJzMY5xkQ3wzWnVPKwW8=",
    "sha256-YllVyCKZAwiQyUGSGXImAfB1BPYsI4NPwfAn3DuOOpY=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-tB5SmdJ+OlpjoFy1LJ+omcY5stuVBwr1WzYIedoBfGo=",
    "sha256-INIgXdHaANJAIJDar5AcBBvnUGgA07oo4q8RSj6ZKz8="
  ],
  "/practices/labor-employment": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-l/rYfFNKdfwypSAe5tiwHqWEEwa17dCvHuYvgiZymO8=",
    "sha256-XQK8RdJVyB7OBCE2e/fobyTRFo3zLLtZ0vsrjbs37U8=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-xY6QOkGk4Ih1NOM0LCUZUvoYtvNuzQfNXwDMxh2tiWA=",
    "sha256-bCtLrJLYan06qCrNZ9Nd2H3/6b3FOY7p0aux4asn6i0="
  ],
  "/practices/pkpu": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-G/5H3YIXG211o4dSPXG+d4m62z6I51JkO7Rxb+++iUM=",
    "sha256-f02QTYF0yUIGMyK4wTp0enjcl6ocitBMQwY8QY7GuHw=",
    "sha256-CIzpTBA2ijQuG3tGy0x9Z+4N0444LgsYM2VyHWZ5afs=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-aVB5mFIKp4/szA6FPiGIH1A2ZNZbUzxSEYsVFbOmRBE=",
    "sha256-NDOBZw5UgvnF4Nn2EuddbNdCkd59eE53aBoeOEZvmWg="
  ],
  "/people/adnan-dika-prawira-wardhana": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-dJ4VJ5jEXFKXO4/WxikY3/8l+y8YkWNJpSxqnNzZfGI=",
    "sha256-Dc6gXfbShZ856CP3CQ7ZTwDbAvk5OkHJP2MCcFa+/As=",
    "sha256-gE95XHqeX/mBovyp+IBgFVXdWYLCzY3Kw26/fbC1tLs=",
    "sha256-hxDSWLFf+yD45jraZlUC22VG/Mw7ksipcaw2X4SZXNM=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/akhmad-fahmi-budiman": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-qc1bnfq8iHkwnpNQCZL9VebQARCQRI3rs6tz0qM7xJc=",
    "sha256-4ICq8PWvHRdp9bQEIWgn7NXNo5A0+R6HKWlvo+TmKPo=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-W3/a4xNazKbc6I0+it8GS/mIqotYcc7AsLqEjBHeAzg=",
    "sha256-FJ4PqR6uZMKjOwjJOxjNzUfbkGqd9vaqiNKaFM2quzc="
  ],
  "/people/andy-arly-gustiawan": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-HOwdLkDjXapGamxR5DaRdB0lYXxSYEvu+Lxso8RtrFA=",
    "sha256-LIaQLQZghCHTV1iUnNRKtuVhHlNuQcqRuPhF+9G+ZEQ=",
    "sha256-BfyMUf0tCkk+NaKl7GpRaa6SdSWWFU64FWzBaMz0mVE=",
    "sha256-fKZJ4jOV9G6ibGSHvGECsHHFMK4ovXqMhaascOzThhQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/arif-gunawan": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-AuSxOaNAksUl/gcNwiQqb4H4PUS2Gh8fVWA36KPgiTU=",
    "sha256-tKJBP7Ojqx+vUttH+ABa2WMeb9jTRNXGTR7vBaPiSLE=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-7oWsOVqHDg05EinSDnXVhnjJPOjkbkzX1XD5ICWM6Yk=",
    "sha256-0PFyPxUtRBzROLaFUiy4bV/+JeOEAfbIIS3u/QCndTs="
  ],
  "/people/benedictus-aryo-bimo": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-3xGyG1yR7xW/EldMcMMrikhO7WluWjQIH91WGz1y0T8=",
    "sha256-tJ+g/DilMj6aBqDtQNm32ad2+ZQfpZLk74qX2csnx44=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-Jy41jgQKcoAGGLiCu51Ss3qYUthgpjzbUMn3U1WaIsA=",
    "sha256-A9NLtTLtqVACTgENyStuAJgfjI5G6linJ7EGVhTjSeA="
  ],
  "/people/betti": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-ijfe8MZK0E5sG4RFO8iHRRI8dXdJKMzxaD0KjkCirjc=",
    "sha256-lz5IkOoSHNkrgRHLOvmhTRO2kaeYHfvi6vgLoHwvB0c=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-lV4jnhy0Ntwx8VAvmxxz4QxEQugKjfdI9fGgNmG8stQ=",
    "sha256-wR4PgoGn4uqUFnW0jUu7q22d0HGH+3Es6Y2V5PWeRhM=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/christian-kharis-wicaksono": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-KSXSOTp94Fb9Ju7lIuJ9NxsBb6sVGsehwA49jhHsjYM=",
    "sha256-x5QiMiD55gGRGGnQ24SEbw7KrVLRrjEp26eDqlW6Iig=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-usCYiTLJC4QAsyjgtyk+QolEHxr9stNa113Jafpt9qk=",
    "sha256-HhBCnKPHDJz18uMKWjwDPfce17kAUpo5fJn8z9D2/48="
  ],
  "/people/dania-agustina": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-5TAqUbsdyuX6VAx83PHaLapS7T+J9VBSOiqUSvwo3Yw=",
    "sha256-FOYfM9IiRQiWbL1EFe6yr/CTm/XT60IkfxpeE8Vr4gc=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-CaOY4JRCZVISbxNnShmbWjhtUl+Lbthl5Xm/WN/jviE=",
    "sha256-RDv2EVEWV7aJ3049YlPMz6h9hizEpY2cGlb8Sc+hCMg="
  ],
  "/people/erwin-hardi-pramana": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-JcfnmYGS5jSWwmtv1Jfg7OW2WxOEkOvYNpW23oRp8dc=",
    "sha256-77xv2y9UT8s4rcurnY09Kko+s8ErRB0mfS12KKghkfY=",
    "sha256-aLXip95lYdfFTtAURCMvtJahYLMbTkIR63Agc1fwRUg=",
    "sha256-N/bZ+vabdi6Qd82S6SEo8NW1pGw0Zo+I7UofqyIA7sc=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/eunike-putri-emmanuella": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-RQWLd295cXEscRgFIgXWNdlBYkArS34d6s4yBsQRMXM=",
    "sha256-zKVoUBDIoFvOIoTqRKRxeB1DOCEHuuXAvL/67nMHuvY=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-LvmysiGgkN4YHSkObCml+VH+y7MkDlMbTm+UJmuzDPI=",
    "sha256-RvLC46VgMxXYsWHRuryO97KWmhJVW+lVa+pCQCiE5k4=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/faras-salwaa-janvira": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-CjNE1RWG1Fghsp2VflHcl6HZlpuqyKq1LnS18a+cWuE=",
    "sha256-q7uThhpaxG3jF2xHlzCeesZd8W8ofE69t0G10/jrbbM=",
    "sha256-Da8yc4p3XRo5oqv80EXIvE2VOij1wfii69AcB7NyvMI=",
    "sha256-8cd87HOvGx4u7qlvQVMVAOHreGGH1wbabaxwPsSzCWA=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/faza-shaqila": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-ArwvA0DSWoMPpth6zzH3iZZj8OILgggWzvizFsrIxh8=",
    "sha256-ZORidCiui/gGL1Z0PHloSeSdGY88C2uTnX5Qp5t7SK8=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-rWXC4hseBTCuKehcS+I5dNA3ByjjUgErYKC1qxe353c=",
    "sha256-1DUj6pxXzsCOXy7z0BkU0VIL11tnXkRBmKaqB1kOld4="
  ],
  "/people/herlin-susanto": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-vV6b5tZ0+PwYKXSWU0EoRGO1vgllkclRmYI0aLLXj8w=",
    "sha256-0aVMFPbeuc+6zUzbC2f46Zx4rWEsNhfo2OIXhwssnd4=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-UNU/fL+4Fwq4RmkCQOjNNZna8SNtq6z2sTHTFeLa1uw=",
    "sha256-xe2mT8BHU4lHYopQBkdGz8op+6MSQohp6tnZFSkv+6k="
  ],
  "/people/indah-try-harsanti": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-JDHBMWKDF1re8Ll+bAlMSJnFnzq9IoyU3zeTAqlldc4=",
    "sha256-dkf0o5DKKn25ZqOXVF9JWE4NBopi99AM+3674u9ke1s=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-lzaHg/u4jEF6wE1WOQci5Lmxh7AnnWq/meb2UsUi4ms=",
    "sha256-ykmrYpr6AuvVaTzMEeOpygo0MlEaIX7KV81p63CkzWA="
  ],
  "/people/meisel-rusli-irawan": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-6W/9n1v876K76HVb6cvWoetnIzpxHeOpC/6WIyz/rXA=",
    "sha256-+LcJH0Xnls+lUwcGG/w/JbfTRky0rxc+iqUlz09pvGY=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-7PYkcu690HwussvIfy49UBTDlZHSG3znLULvSStVYfc=",
    "sha256-UadbwSQ/8CaZrwPER1Ow9wZd0OyU1DIY917VJxZwg1o="
  ],
  "/people/muhamad-arifudin": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-qcsFceRfuzREenV5Ae9OgXl6hFiPUDqMcndPvWzqALU=",
    "sha256-7xswxn5AYSH/AVFgF6VrHovEbuBXaMlmPrSIZantiUc=",
    "sha256-wCw6kgvlQB7r1a4yLgTEV34eXUVffiGlcflgdgFe+M4=",
    "sha256-5nU1LVd78FtoA3+waTXZp5umAjNsEQZvrHAhVS9dw+w=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/muhammad-agung-laksana": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-M8KHJV+86N38OOB+S4AQuaYhc1CE/pGKYlBVRvKIq58=",
    "sha256-tn3B5sS/DwbV2cFYi0s4HtactQvtOLujVPPbrWByrMM=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-JZmm16q4OH4kPbiro+RSmJu2I6nqYmjU43Vo9bWHyQE=",
    "sha256-qtZEyIxFr1ni8CjLu28bKmvGrGbqAS5YNPhdWSf9+g4="
  ],
  "/people/muhammad-rizki-aditya": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-56Eq9QZAwwjw5e2LuxAj1lCGCnJJh/JuLd3B15oITcA=",
    "sha256-nBotSt4a9irjSa2WYkMc2mHmAVYIPUEhIZqCMYanA/0=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-0RWaGc4GtfjQi0OkdQbZ6F/SWY1unyRpj7h0ci6+wxc=",
    "sha256-m21cCnme0HjwnLr4SMoYYgSBKs5sjvOurNsVUgSq3i8="
  ],
  "/people/nurhadi-islami": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-FiHE/ikCKj9tYT6uJV0FBoFfuzfaMOOhswo92GDy4R4=",
    "sha256-BMskhMp28CrwfvCIc6GEktxr6JyhBFsm62+TTL8G3CU=",
    "sha256-mRcdKZIaOUnNjGIeu7Z8flQVcGdgNARLMAke2H9xZB4=",
    "sha256-0DpcZDEa1c9nsG/PlkFDOpQIpkk6P8TeFFAmr55MCc8=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/rakhmadani-hutama": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-LD6+xj4XcNv8BtpuFY+qjBXyWxGhF3yct3+Tgykm7dE=",
    "sha256-GtbGbwC1ZfdmC14FPFtURyq0lNOnCz8QynqKupaAOLM=",
    "sha256-/aaobdIv2l8LcurJCLb17JOLPFMl7FwfiXCdQfdHWS0=",
    "sha256-TqcNpGYJ6LsDvbMq1Zq/z73PVGZ48dnYs+GZ8/Vd5Nw=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/ratna-sumirat": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-ITZILYGdLUPvjs68uDon55TTYzI2D8BZFDfIt50yCr8=",
    "sha256-qbPoNyCecPvh5RnG6AfUyhudvFXykbO11DO7Z2wkqrM=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-/nGbQ34Xz9lAAvvtZet64ZN8/PSDSTgQNT+q5x5ST7Y=",
    "sha256-Baibxpzxcp186Pl9tYuI4BQCr/aeqtJx5++MFEKKYFk="
  ],
  "/people/reza-rahmawati": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-W2EnpN4RPzZW6Qr4K4B3ZyxNwCr9grJeZJB6ILgvtts=",
    "sha256-b+fGpCO8NLueoiTHC3qz0JXi3VGEszau0j/cV2S2Caw=",
    "sha256-Zh0PS3r/7lMIyouio1ISy5rJcpuTpABYVjcv/VksvZQ=",
    "sha256-GlxCtLmqKBMvmSssvGOZYnmWrwG3y8sqAMANw6nkO48=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
  ],
  "/people/richard-goenawan": [
    "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
    "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
    "sha256-TKC0zTnD1UPlbIR1o7Fykv/RqpAR6B4pERR+dBUGt6w=",
    "sha256-36qBxWYUp+8Jqufr48qoHvpzg5UPisR1XA2HGUZxU1Q=",
    "sha256-CcE5mtj/HFCZskfLxvOKfhyqDAK7bh8Zr//s2V52HcQ=",
    "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0=",
    "sha256-hhZ4ZxQ+5hTkJPSXaSg4J0QZWTPV362SCI7ENo8mmww=",
    "sha256-u52Ohz3TVJLTxWnoFObB3/V7efBJlHEz3bEjReVwb2Y="
  ]
};

export const CSP_COMMON_SCRIPT_HASHES: string[] = [
  "sha256-Q+8tPsjVtiDsjF/Cv8FMOpg2Yg91oKFKDAJat1PPb2g=",
  "sha256-WVHstWgxVWMbLAFDTDXQDjuxI19zQ+VaLneyVxcV5go=",
  "sha256-t1M2cSQ7fbm1e6VGgzrkBAhfnGquCEjd3iJjg24sR/0="
];
