-- Generated by db/seed.py from data/*.json. Do not hand-edit; edit the JSON and regenerate.
BEGIN;

-- firm_settings: singleton row. Everything here is what firm.json already had —
-- no new fact is introduced, this just gives it a table instead of lib/data.ts
-- reading the JSON file directly.
INSERT INTO firm_settings (id, legal_name, short_name, founded, founders, core_values, office_name, office_street, office_district, office_city, office_region, office_postal_code, office_country, office_phone, office_email, office_geo_lat, office_geo_lng, office_opening_hours, office_linkedin_url, claimed_fee_earners, claimed_practice_areas, claimed_clients, claimed_metrics_warning) VALUES (true, 'Arifudin Susanto Partnership', 'ASP', '2017-05-03', ARRAY['Muhamad Arifudin', 'Herlin Susanto']::text[], ARRAY['Visionary', 'Integrity', 'Professional']::text[], 'ASP Building', 'Jl. Mampang Prapatan Raya No. 26, RT.2/RW.1', 'Duren Tiga, Pancoran', 'Jakarta Selatan', 'DKI Jakarta', '12760', 'ID', '+62 21 38815231', 'office@asplawyer.co.id', NULL, NULL, NULL, NULL, 40, 10, 237, 'Legacy homepage claims 40 fee earners but only 23 people are listed on /our-people/. Must be reconciled before launch.') ON CONFLICT (id) DO UPDATE SET legal_name = EXCLUDED.legal_name, short_name = EXCLUDED.short_name, founded = EXCLUDED.founded, founders = EXCLUDED.founders, core_values = EXCLUDED.core_values, office_name = EXCLUDED.office_name, office_street = EXCLUDED.office_street, office_district = EXCLUDED.office_district, office_city = EXCLUDED.office_city, office_region = EXCLUDED.office_region, office_postal_code = EXCLUDED.office_postal_code, office_country = EXCLUDED.office_country, office_phone = EXCLUDED.office_phone, office_email = EXCLUDED.office_email, office_geo_lat = EXCLUDED.office_geo_lat, office_geo_lng = EXCLUDED.office_geo_lng, office_opening_hours = EXCLUDED.office_opening_hours, office_linkedin_url = EXCLUDED.office_linkedin_url, claimed_fee_earners = EXCLUDED.claimed_fee_earners, claimed_practice_areas = EXCLUDED.claimed_practice_areas, claimed_clients = EXCLUDED.claimed_clients, claimed_metrics_warning = EXCLUDED.claimed_metrics_warning, updated_at = now();

-- lawyers: all 23 published (names/tiers are verified; missing bios render
-- as an empty state in the app, same as the prototype, not as a publish-block).
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('muhamad-arifudin', 'Muhamad Arifudin', 'S.H., M.H.', 'managing-partner'::lawyer_tier, 'Managing Partner', true, NULL, 0, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('herlin-susanto', 'Herlin Susanto', 'S.H., M.H.', 'founding-partner'::lawyer_tier, 'Founding Partner', false, NULL, 10, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('akhmad-fahmi-budiman', 'Akhmad Fahmi Budiman', 'S.H., M.H.', 'counsel'::lawyer_tier, 'Leader', false, NULL, 20, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('rakhmadani-hutama', 'Rakhmadani Hutama', 'S.H., M.H.', 'counsel'::lawyer_tier, 'Leader', false, NULL, 30, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('muhammad-agung-laksana', 'Muhammad Agung Laksana', 'S.H.', 'counsel'::lawyer_tier, 'Leader', false, NULL, 40, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('adnan-dika-prawira-wardhana', 'Adnan Dika Prawira Wardhana', 'S.H., M.H.', 'counsel'::lawyer_tier, 'Leader', false, NULL, 50, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('indah-try-harsanti', 'Indah Try Harsanti', 'S.H.', 'counsel'::lawyer_tier, 'Leader', false, NULL, 60, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('muhammad-rizki-aditya', 'Muhammad Rizki Aditya', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 70, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('reza-rahmawati', 'Reza Rahmawati', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 80, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('christian-kharis-wicaksono', 'Christian Kharis Wicaksono', 'S.H., M.Kn.', 'associate'::lawyer_tier, 'Associate', false, NULL, 90, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('betti', 'Betti', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 100, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('dania-agustina', 'Dania Agustina', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 110, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('erwin-hardi-pramana', 'Erwin Hardi Pramana', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 120, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('faras-salwaa-janvira', 'Faras Salwaa Janvira', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 130, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('ratna-sumirat', 'Ratna Sumirat', 'S.H., M.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 140, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('arif-gunawan', 'Arif Gunawan', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 150, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('nurhadi-islami', 'Nurhadi Islami', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 160, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('andy-arly-gustiawan', 'Andy Arly Gustiawan', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 170, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('benedictus-aryo-bimo', 'Benedictus Aryo Bimo', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 180, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('eunike-putri-emmanuella', 'Eunike Putri Emmanuella', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 190, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('faza-shaqila', 'Faza Shaqila', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 200, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('meisel-rusli-irawan', 'Meisel Rusli Irawan', 'S.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 210, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) VALUES ('richard-goenawan', 'Richard Goenawan', 'S.H., M.H.', 'associate'::lawyer_tier, 'Associate', false, NULL, 220, true) ON CONFLICT (slug) DO NOTHING;

-- lawyer_translations: only the two founders have a publishable bio.
INSERT INTO lawyer_translations (lawyer_id, locale, bio_full) SELECT id, 'en'::locale, 'Lawyer and court-appointed bankruptcy receiver, and managing partner of the firm. More than fifteen years of practice in bankruptcy and debt restructuring, across energy, oil and gas, aviation, plantations and palm oil processing, investment companies, cooperatives, property, warehousing, tobacco, manufacturing, textiles, herbal medicine production, shipping, mobile dealerships and individual debtor matters. Has acted for state-owned enterprises both as court-appointed receiver and as counsel.' FROM lawyers WHERE slug = 'muhamad-arifudin' ON CONFLICT (lawyer_id, locale) DO NOTHING;
INSERT INTO lawyer_translations (lawyer_id, locale, bio_full) SELECT id, 'en'::locale, 'Co-founder and partner. Law degree from Universitas Gadjah Mada and a master''s in law from Universitas Sriwijaya. More than fifteen years in bankruptcy, PKPU, litigation and arbitration, representing national companies in business disputes and corporate restructuring. Serves as treasurer of the honorary board of the Indonesian Association of Curators and Administrators (AKPI) for the 2025-2028 term.' FROM lawyers WHERE slug = 'herlin-susanto' ON CONFLICT (lawyer_id, locale) DO NOTHING;

-- lawyer_credentials: only what the firm has already published for Herlin Susanto.
INSERT INTO lawyer_credentials (lawyer_id, kind, value, year) SELECT id, 'education', 'Universitas Gadjah Mada', NULL FROM lawyers WHERE slug = 'herlin-susanto';
INSERT INTO lawyer_credentials (lawyer_id, kind, value, year) SELECT id, 'education', 'Universitas Sriwijaya (LL.M.)', NULL FROM lawyers WHERE slug = 'herlin-susanto';
INSERT INTO lawyer_credentials (lawyer_id, kind, value, year) SELECT id, 'membership', 'Indonesian Association of Curators and Administrators (AKPI) — treasurer, honorary board, 2025-2028', NULL FROM lawyers WHERE slug = 'herlin-susanto';

-- practice_areas: seeded UNPUBLISHED. data/lawyers.json has no lawyer -> practice
-- links (every lawyer's practice_areas array is empty — content request 1), so no
-- practice has a lead. practice_lead_guard is expected to refuse is_published=true
-- until ASP assigns one; see db/verify_guards.sql.
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('bankruptcy', 'flagship'::practice_tier, 'Bankruptcy, PKPU & Restructuring', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Bankruptcy' FROM practice_areas WHERE slug = 'bankruptcy' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Kepailitan' FROM practice_areas WHERE slug = 'bankruptcy' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('pkpu', 'flagship'::practice_tier, 'Bankruptcy, PKPU & Restructuring', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'PKPU (Suspension of Debt Payment Obligations)' FROM practice_areas WHERE slug = 'pkpu' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'PKPU' FROM practice_areas WHERE slug = 'pkpu' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('debt-restructuring', 'flagship'::practice_tier, 'Bankruptcy, PKPU & Restructuring', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Debt Restructuring' FROM practice_areas WHERE slug = 'debt-restructuring' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Restrukturisasi Utang' FROM practice_areas WHERE slug = 'debt-restructuring' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('commercial-litigation', 'dispute'::practice_tier, 'Commercial Litigation', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Commercial Litigation' FROM practice_areas WHERE slug = 'commercial-litigation' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Litigasi Komersial' FROM practice_areas WHERE slug = 'commercial-litigation' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('civil-litigation', 'dispute'::practice_tier, 'Civil Litigation', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Civil Litigation' FROM practice_areas WHERE slug = 'civil-litigation' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Litigasi Perdata' FROM practice_areas WHERE slug = 'civil-litigation' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('criminal-litigation', 'dispute'::practice_tier, 'Criminal Litigation', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Criminal Litigation' FROM practice_areas WHERE slug = 'criminal-litigation' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Litigasi Pidana' FROM practice_areas WHERE slug = 'criminal-litigation' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('arbitration', 'dispute'::practice_tier, 'Arbitration', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Arbitration' FROM practice_areas WHERE slug = 'arbitration' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Arbitrase' FROM practice_areas WHERE slug = 'arbitration' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('dispute-resolution', 'dispute'::practice_tier, 'Dispute Resolution', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Dispute Resolution' FROM practice_areas WHERE slug = 'dispute-resolution' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Penyelesaian Sengketa' FROM practice_areas WHERE slug = 'dispute-resolution' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('labor-employment', 'corporate'::practice_tier, 'Labor and Employment', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Labor & Employment' FROM practice_areas WHERE slug = 'labor-employment' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Ketenagakerjaan' FROM practice_areas WHERE slug = 'labor-employment' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('capital-markets', 'corporate'::practice_tier, 'Capital Markets', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Capital Markets' FROM practice_areas WHERE slug = 'capital-markets' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Pasar Modal' FROM practice_areas WHERE slug = 'capital-markets' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('competition-antitrust', 'corporate'::practice_tier, 'Competition & Antitrust', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Competition & Antitrust' FROM practice_areas WHERE slug = 'competition-antitrust' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Persaingan Usaha' FROM practice_areas WHERE slug = 'competition-antitrust' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_areas (slug, tier, legacy_group, is_published) VALUES ('islamic-law', 'corporate'::practice_tier, 'Islamic Law', false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'en'::locale, 'Islamic Law' FROM practice_areas WHERE slug = 'islamic-law' ON CONFLICT (practice_id, locale) DO NOTHING;
INSERT INTO practice_translations (practice_id, locale, name) SELECT id, 'id'::locale, 'Hukum Islam' FROM practice_areas WHERE slug = 'islamic-law' ON CONFLICT (practice_id, locale) DO NOTHING;

-- industries, article_categories: structural taxonomies, map straight onto the schema.
-- sort_order = JSON array position — the only 'curated order' available to preserve.
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('manufacturing', 'Manufacturing', 'Manufaktur', 0) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('aviation', 'Aviation', 'Penerbangan', 10) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('shipping', 'Shipping', 'Pelayaran', 20) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('oil-gas-energy', 'Oil & Gas and Energy Exploration', 'Migas & Energi', 30) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('property-real-estate', 'Property & Real Estate', 'Properti & Real Estat', 40) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('tobacco', 'Tobacco', 'Tembakau', 50) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('plantation-palm-oil', 'Plantation & Palm Oil Processing', 'Perkebunan & Pengolahan Sawit', 60) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('cooperatives-microfinance', 'Cooperatives & Microfinance', 'Koperasi & Lembaga Keuangan Mikro', 70) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('umrah-hajj-travel', 'Umrah and Hajj Travel', 'Travel Umrah & Haji', 80) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('textiles-garments', 'Textiles & Garments', 'Tekstil & Garmen', 90) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('investment-firms', 'Investment Firms', 'Perusahaan Investasi', 100) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('cellular-dealership', 'Cellular Dealership', 'Dealer Seluler', 110) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('warehousing', 'Warehousing', 'Pergudangan', 120) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('herbal-medicine', 'Traditional Herbal Medicine (Jamu)', 'Jamu', 130) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('soe', 'State-Owned Enterprises', 'BUMN', 140) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO industries (slug, name_en, name_id, sort_order) VALUES ('listed-companies', 'Publicly Listed Companies (Tbk)', 'Perusahaan Terbuka (Tbk)', 150) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('legal-update', 'Legal Update', 'Pembaruan Hukum', 0) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('bankruptcy', 'Bankruptcy', 'Kepailitan', 10) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('pkpu', 'PKPU', 'PKPU', 20) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('restructuring', 'Restructuring', 'Restrukturisasi', 30) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('litigation', 'Litigation', 'Litigasi', 40) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('corporate', 'Corporate', 'Korporasi', 50) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('arbitration', 'Arbitration', 'Arbitrase', 60) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('employment', 'Employment', 'Ketenagakerjaan', 70) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO article_categories (slug, name_en, name_id, sort_order) VALUES ('case-analysis', 'Case Analysis', 'Analisis Perkara', 80) ON CONFLICT (slug) DO UPDATE SET sort_order = EXCLUDED.sort_order;

-- awards: source_url is NOT NULL in the schema and present for all 10 — no gap here.
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('best-litigation-brand-innovation-2026', 'Best Litigation Law Firm Brand Innovation of The Year 2026', 2026, 'Hukumonline', 'https://awards.hukumonline.com/top-100-law-firms-2026/best-litigation-law-firms-for-brand-innovation-2026/arifudin-susanto-partnership', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('top-10-largest-litigation-2026', '3rd Place — Top 10 Largest Litigation Practice Law Firm of The Year 2026', 2026, 'Hukumonline', 'https://awards.hukumonline.com/top-100-law-firms-2026/top-10-largest-litigation-law-firms-2026/arifudin-susanto-partnership', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('elite-one-bankruptcy-2026', 'Elite One Practice Leader 2026 — Bankruptcy, Insolvency & Restructuring', 2026, 'Hukumonline', 'https://www.hukumonline.com/practice-leaders/arifudin-and-susanto-partnership-asp-law-firm/', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('elite-one-islamic-finance-2026', 'Elite One Practice Leader 2026 — Islamic Finance', 2026, 'Hukumonline', 'https://www.hukumonline.com/practice-leaders/arifudin-and-susanto-partnership-asp-law-firm/', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('top-100-indonesian-law-firms-2026', 'Top 100 Indonesian Law Firms of The Year 2026', 2026, 'Hukumonline', 'https://awards.hukumonline.com/top-100-law-firms-2026/top-100-indonesian-law-firms-2026/arifudin-susanto-partnership', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('elite-one-labor-employment-2025', 'Practice Leaders 2025 — Elite One in Labor & Employment', 2025, 'Hukumonline', 'https://www.hukumonline.com/practice-leaders/', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('elite-one-arbitration-litigation-2025', 'Practice Leaders 2025 — Elite One in Arbitration, Litigation & Dispute Resolution', 2025, 'Hukumonline', 'https://www.hukumonline.com/practice-leaders/', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('elite-one-bankruptcy-2024', 'Practice Leaders 2024 — Elite One in Bankruptcy, Insolvency and Restructuring', 2024, 'Hukumonline', 'https://www.hukumonline.com/berita/a/peluncuran-direktori-practice-leaders-lt668249183a6a5/', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('largest-litigation-4th-2024', '4th Place — Largest Litigation Practice Law Firm of The Year 2024', 2024, 'Hukumonline', 'https://awards.hukumonline.com/top-100-law-firms-2024', true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO awards (slug, title, year, organization, source_url, is_published) VALUES ('top-10-largest-litigation-2022', '3rd Place — Top 10 Largest Litigation Practice Law Firm 2022', 2022, 'Hukumonline', 'https://www.hukumonline.com/berita/a/ini-jajaran-kantor-hukum-terbesar-kategori-litigasi-2022-lt6315a4859c5eb/', true) ON CONFLICT (slug) DO NOTHING;

-- redirects: only real HTTP redirects (301/410) fit this table's CHECK constraint.
-- 5 rows in redirects.csv do not and are excluded on purpose, not by oversight:
--   status=200 (/careers/ -> /careers/, 'unchanged') is not a redirect at all;
--   status=BLOCK (4 legacy WordPress paths) is a WAF/robots rule, not an HTTP
--   redirect — that belongs in config/security-headers.js + Cloudflare (Phase 6),
--   not this table. See docs/content-requests.md-adjacent finding in db/verify_guards.sql output.
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/about-us/', '/about/firm/', 301, NULL) ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/our-people/', '/people/', 301, NULL) ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/solutions/', '/practices/', 301, 'menu label was ''Practice Area''') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/news/', '/insights/', 301, 'legacy only held dummy posts') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/contact-us/', '/contact/', 301, NULL) ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/about-us/', '/id/tentang/profil/', 301, NULL) ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/our-people/', '/id/tim/', 301, NULL) ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/solutions/', '/id/layanan/', 301, NULL) ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/news/', '/id/wawasan/', 301, NULL) ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/contact-us/', '/id/kontak/', 301, NULL) ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/careers/', '/careers/', 301, 'ID mirror of an unchanged EN page; no dedicated /id/ careers page yet') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/en/*', '/*', 301, 'EN stays at root') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/hello-world/', NULL, 410, 'WordPress default post') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/be-my-guest/', NULL, 410, 'theme demo post') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/nulla-magna/', NULL, 410, 'theme demo post') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/category/fashion/', NULL, 410, 'dummy taxonomy') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/category/music/', NULL, 410, 'dummy taxonomy') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/category/uncategorized/', NULL, 410, 'dummy taxonomy') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/author/asplawyer/', NULL, 410, 'WordPress default author archive; not in the original nav crawl') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/hello-world/', NULL, 410, 'TranslatePress ID mirror of the same WordPress default post') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/be-my-guest/', NULL, 410, 'TranslatePress ID mirror of the same theme demo post') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/nulla-magna/', NULL, 410, 'TranslatePress ID mirror of the same theme demo post') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/category/fashion/', NULL, 410, 'TranslatePress ID mirror of the same dummy taxonomy') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/category/music/', NULL, 410, 'TranslatePress ID mirror of the same dummy taxonomy') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/category/uncategorized/', NULL, 410, 'TranslatePress ID mirror of the same dummy taxonomy') ON CONFLICT (from_path) DO NOTHING;
INSERT INTO redirects (from_path, to_path, status, note) VALUES ('/id/author/asplawyer/', NULL, 410, 'TranslatePress ID mirror of the same author archive') ON CONFLICT (from_path) DO NOTHING;

-- Deliberately NOT seeded: cases (no matter is cleared — content request 6),
-- articles (nothing published yet — editorial-calendar.md), users, media, leads,
-- events, jobs, knowledge_topics, seo_metadata. Seeding any of these would mean
-- inventing content the firm has not supplied.

COMMIT;
