#!/usr/bin/env python3
"""Generate db/seed.sql from data/*.json — the Phase 4 step docs/04-cms-backend.md §6
asked for: "apply against a scratch instance, load data/*.json as the seed, and confirm
the four integrity guards actually reject bad rows."

Same rule as build.py and lib/data.ts: nothing here is invented. Every row traces to a
field that already exists in data/*.json. Where ASP has not supplied something (bios for
21 of 23 lawyers, practice overviews, article authors, cleared matters), the row — or the
whole table — is simply not seeded, same as the prototype renders an empty state instead
of placeholder prose.

Usage:  python3 db/seed.py > db/seed.sql
        psql -d asp_legal_dev -v ON_ERROR_STOP=1 -f db/seed.sql
"""

import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")


def load(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as f:
        return json.load(f)


def q(value):
    """SQL string literal, or NULL."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def qb(value):
    return "true" if value else "false"


FIRM = load("firm.json")
LAWYERS = load("lawyers.json")["lawyers"]
PRACTICES = load("practice-areas.json")["practice_areas"]
AWARDS = load("awards.json")["awards"]
INDUSTRIES = load("industries.json")["industries"]
CATEGORIES = load("insight-categories.json")["insight_categories"]

# Tier naming is an open decision (CLAUDE.md, decision D-03: legacy site says
# "Leaders", the brief says "Counsel"). The schema's lawyer_tier enum has no
# "leader" value and needs one to seed at all, so this maps leader -> counsel
# as the brief's proposed name — a technical mapping to satisfy the enum, not
# a resolution of the open decision. Flagged here and in the seed's own
# output; do not remove the flag until ASP actually decides.
TIER_MAP = {
    "managing-partner": "managing-partner",
    "founding-partner": "founding-partner",
    "partner": "partner",
    "leader": "counsel",  # <-- provisional, see comment above
    "associate": "associate",
}

# Verbatim from lib/data.ts / prototype/build.py's BIO_SUMMARY — the only two
# lawyers with publishable expertise today (docs/editorial-calendar.md §2).
BIO_FULL = {
    "muhamad-arifudin": (
        "Lawyer and court-appointed bankruptcy receiver, and managing partner of the firm. "
        "More than fifteen years of practice in bankruptcy and debt restructuring, across energy, "
        "oil and gas, aviation, plantations and palm oil processing, investment companies, cooperatives, "
        "property, warehousing, tobacco, manufacturing, textiles, herbal medicine production, shipping, "
        "mobile dealerships and individual debtor matters. Has acted for state-owned enterprises both as "
        "court-appointed receiver and as counsel."
    ),
    "herlin-susanto": (
        "Co-founder and partner. Law degree from Universitas Gadjah Mada and a master's in law from "
        "Universitas Sriwijaya. More than fifteen years in bankruptcy, PKPU, litigation and arbitration, "
        "representing national companies in business disputes and corporate restructuring. Serves as "
        "treasurer of the honorary board of the Indonesian Association of Curators and Administrators (AKPI) "
        "for the 2025-2028 term."
    ),
}

out = []
out.append("-- Generated by db/seed.py from data/*.json. Do not hand-edit; edit the JSON and regenerate.")
out.append("BEGIN;\n")

# ---------------------------------------------------------------- lawyers ---
out.append("-- lawyers: all 23 published (names/tiers are verified; missing bios render")
out.append("-- as an empty state in the app, same as the prototype, not as a publish-block).")
for i, l in enumerate(LAWYERS):
    tier = TIER_MAP[l["tier"]]
    out.append(
        f"INSERT INTO lawyers (slug, name, honorifics, tier, position_label, is_curator, email, sort_order, is_published) "
        f"VALUES ({q(l['slug'])}, {q(l['name'])}, {q(l['honorifics'])}, {q(tier)}::lawyer_tier, "
        f"{q(l['position'])}, {qb(l['is_curator'])}, {q(l['email'])}, {i * 10}, true) "
        f"ON CONFLICT (slug) DO NOTHING;"
    )
out.append("")

out.append("-- lawyer_translations: only the two founders have a publishable bio.")
for slug, bio in BIO_FULL.items():
    out.append(
        f"INSERT INTO lawyer_translations (lawyer_id, locale, bio_full) "
        f"SELECT id, 'en'::locale, {q(bio)} FROM lawyers WHERE slug = {q(slug)} "
        f"ON CONFLICT (lawyer_id, locale) DO NOTHING;"
    )
out.append("")

out.append("-- lawyer_credentials: only what the firm has already published for Herlin Susanto.")
CREDENTIALS = [
    ("herlin-susanto", "education", "Universitas Gadjah Mada", None),
    ("herlin-susanto", "education", "Universitas Sriwijaya (LL.M.)", None),
    (
        "herlin-susanto",
        "membership",
        "Indonesian Association of Curators and Administrators (AKPI) — treasurer, honorary board, 2025-2028",
        None,
    ),
]
for slug, kind, value, year in CREDENTIALS:
    out.append(
        f"INSERT INTO lawyer_credentials (lawyer_id, kind, value, year) "
        f"SELECT id, {q(kind)}, {q(value)}, {year if year else 'NULL'} FROM lawyers WHERE slug = {q(slug)};"
    )
out.append("")

# -------------------------------------------------------------- practices ---
out.append("-- practice_areas: seeded UNPUBLISHED. data/lawyers.json has no lawyer -> practice")
out.append("-- links (every lawyer's practice_areas array is empty — content request 1), so no")
out.append("-- practice has a lead. practice_lead_guard is expected to refuse is_published=true")
out.append("-- until ASP assigns one; see db/verify_guards.sql.")
for p in PRACTICES:
    out.append(
        f"INSERT INTO practice_areas (slug, tier, legacy_group, is_published) "
        f"VALUES ({q(p['slug'])}, {q(p['tier'])}::practice_tier, {q(p['legacy_group'])}, false) "
        f"ON CONFLICT (slug) DO NOTHING;"
    )
    for locale, name in (("en", p["name_en"]), ("id", p["name_id"])):
        out.append(
            f"INSERT INTO practice_translations (practice_id, locale, name) "
            f"SELECT id, {q(locale)}::locale, {q(name)} FROM practice_areas WHERE slug = {q(p['slug'])} "
            f"ON CONFLICT (practice_id, locale) DO NOTHING;"
        )
out.append("")

# ------------------------------------------------------------- taxonomies ---
out.append("-- industries, article_categories: structural taxonomies, map straight onto the schema.")
for ind in INDUSTRIES:
    out.append(
        f"INSERT INTO industries (slug, name_en, name_id) VALUES "
        f"({q(ind['slug'])}, {q(ind['name_en'])}, {q(ind['name_id'])}) ON CONFLICT (slug) DO NOTHING;"
    )
for cat in CATEGORIES:
    out.append(
        f"INSERT INTO article_categories (slug, name_en, name_id) VALUES "
        f"({q(cat['slug'])}, {q(cat['name_en'])}, {q(cat['name_id'])}) ON CONFLICT (slug) DO NOTHING;"
    )
out.append("")

# ----------------------------------------------------------------- awards ---
out.append("-- awards: source_url is NOT NULL in the schema and present for all 10 — no gap here.")
for a in AWARDS:
    out.append(
        f"INSERT INTO awards (slug, title, year, organization, source_url, is_published) "
        f"VALUES ({q(a['slug'])}, {q(a['title'])}, {a['year']}, {q(a['organization'])}, "
        f"{q(a['source_url'])}, true) ON CONFLICT (slug) DO NOTHING;"
    )
out.append("")

# ------------------------------------------------------------- redirects ---
out.append("-- redirects: only real HTTP redirects (301/410) fit this table's CHECK constraint.")
out.append("-- 5 rows in redirects.csv do not and are excluded on purpose, not by oversight:")
out.append("--   status=200 (/careers/ -> /careers/, 'unchanged') is not a redirect at all;")
out.append("--   status=BLOCK (4 legacy WordPress paths) is a WAF/robots rule, not an HTTP")
out.append("--   redirect — that belongs in config/security-headers.js + Cloudflare (Phase 6),")
out.append("--   not this table. See docs/content-requests.md-adjacent finding in db/verify_guards.sql output.")
with open(os.path.join(DATA, "redirects.csv"), encoding="utf-8") as f:
    for row in csv.DictReader(f):
        status = row["status"].strip()
        if status not in ("301", "302", "410"):
            continue
        to_path = row["new_path"].strip() or None
        out.append(
            f"INSERT INTO redirects (from_path, to_path, status, note) VALUES "
            f"({q(row['old_path'].strip())}, {q(to_path)}, {status}, {q(row['note'].strip() or None)}) "
            f"ON CONFLICT (from_path) DO NOTHING;"
        )
out.append("")

out.append("-- Deliberately NOT seeded: cases (no matter is cleared — content request 6),")
out.append("-- articles (nothing published yet — editorial-calendar.md), users, media, leads,")
out.append("-- events, jobs, knowledge_topics, seo_metadata. Seeding any of these would mean")
out.append("-- inventing content the firm has not supplied.")
out.append("")
out.append("COMMIT;")

print("\n".join(out))
